/**
 * Shared URL → MenuItemData[] extractor.
 *
 * Fetches any URL (restaurant website, Yelp menu link) and pulls
 * dish names, descriptions, and photo URLs from multiple sources.
 *
 * Platform detection order (first match wins):
 *   1. Menufy / HungerRush — web-component ordering sites.
 *      Detection: `api.menufy.com` in HTML.
 *      Data: direct API at api.menufy.com → falls back to Scrapfly render.
 *      Photos: static.hungerrush.com CDN — 300×300, scaled to 800×800.
 *      Coverage: thousands of independent US restaurants.
 *
 *   2. Schema.org LD+JSON — auto-generated by Toast, Square, Squarespace, Wix, Olo.
 *      Coverage: ~35–50% of restaurants with a website.
 *
 * Called by:
 *   - google.ts  → restaurant's own website (Place Details `website` field)
 *   - yelp.ts    → Yelp business `attributes.menu_url`
 */

import { MenuItemData } from "./types";

export async function fetchMenuFromUrl(url: string): Promise<MenuItemData[]> {
  try {
    const res = await fetch(url, {
      signal: AbortSignal.timeout(6000),
      headers: {
        "User-Agent": "Mozilla/5.0 (compatible; SeeFood/1.0)",
        Accept: "text/html,application/xhtml+xml",
      },
    });
    if (!res.ok) {
      console.log(`[fetchMenuFromUrl] ${url} → HTTP ${res.status}`);
      return [];
    }
    const html = await res.text();

    // ── Platform 1: Menufy / HungerRush ───────────────────────────────────────
    if (html.includes("api.menufy.com")) {
      const items = await parseMenufySite(url, html);
      if (items.length > 0) return items;
    }

    // ── Platform 1b: Menufy via order link ───────────────────────────────────
    // Some restaurants (e.g. Richie's Diner) have their marketing site separate
    // from their Menufy ordering site, sometimes chained through an intermediate
    // "/order" redirect page. Follow up to 3 hops.
    const menufyViaSideLink = await checkLinksForMenufy(url, html, 3);
    if (menufyViaSideLink.length > 0) return menufyViaSideLink;

    // ── Platform 2: Schema.org LD+JSON ────────────────────────────────────────
    return parseSchemaOrgMenuItems(html);
  } catch (e) {
    console.error(`[fetchMenuFromUrl] ${url} failed:`, e);
    return [];
  }
}

// ── Menufy / HungerRush ───────────────────────────────────────────────────────
//
// Architecture:
//   Web components (<new-menufy-item-card>) are populated from api.menufy.com.
//   The raw HTML exposes location-id + api-key in <location-context> attributes.
//   The data is NOT in the raw HTML (JS-rendered), so we need one of:
//     A. Direct API call to api.menufy.com (fast, free, no credits)
//     B. Scrapfly render_js=true to get fully-rendered DOM (needs SCRAPFLY_KEY)
//
// Each item card attribute pattern:
//   item-name="Baby Back BBQ Ribs"
//   item-description="2 full racks..."
//   item-image-url="https://static.hungerrush.com/menufy/width=300,.../{ts}+{id}.png"
//   item-price="89.95"  item-id="12331076"  category-id="1131672"

function extractMenufyParams(html: string): { locationId: string; apiKey: string } | null {
  const locationMatch = html.match(/location-id="(\d+)"/);
  const apiKeyMatch   = html.match(/api-key="([A-Za-z0-9+/=]{8,})"/);
  if (!locationMatch || !apiKeyMatch) return null;
  return { locationId: locationMatch[1], apiKey: apiKeyMatch[1] };
}

/**
 * Follow "order" / "menu" links on the main website to find a Menufy
 * ordering site that's hosted at a different domain.
 * Example: richiesdiner.com → richiesdinertemecula.com (Menufy)
 */
async function checkLinksForMenufy(
  baseUrl: string,
  html: string,
  depthRemaining: number,
  visited: Set<string> = new Set()
): Promise<MenuItemData[]> {
  if (depthRemaining <= 0) return [];
  visited.add(baseUrl);
  let baseOrigin = "";
  try { baseOrigin = new URL(baseUrl).origin; } catch { return []; }

  // Find candidate links from actual anchor tags only — <a href="...">,
  // NOT <link>/<img>/<script> resource hrefs (favicons, fonts, CDN assets),
  // which otherwise flood the candidate list and crowd out the real link.
  const anchorPattern = /<a\s[^>]*href="([^"]+)"/gi;
  const STATIC_ASSET_RE = /\.(css|js|png|jpe?g|gif|svg|ico|woff2?|ttf|eot|json|xml|webmanifest)(\?|#|$)/i;
  const NON_CONTENT_HOSTS = [
    "facebook.com","instagram.com","yelp.com","google.com","tripadvisor.com","twitter.com","x.com",
    "tiktok.com","doordash.com","ubereats.com","grubhub.com","typekit.net","adobedtm.com",
    "cookielaw.org","squarespace-cdn.com","squarespace.com","googletagmanager.com","google-analytics.com",
  ];

  const orderCandidates: string[] = [];
  const externalCandidates: string[] = [];
  let m: RegExpExecArray | null;

  while ((m = anchorPattern.exec(html)) !== null) {
    const href = m[1];
    if (!href || href.startsWith("#") || href.startsWith("javascript") ||
        href.startsWith("mailto") || href.startsWith("tel")) continue;
    if (STATIC_ASSET_RE.test(href)) continue;

    // Order/menu keywords in relative paths
    const isOrderPath = /\/(order|menu|delivery|online-order)/i.test(href);

    let isExternal = false;
    let resolvedUrl = href;
    if (href.startsWith("http")) {
      try {
        const u = new URL(href);
        isExternal = u.origin !== baseOrigin && !NON_CONTENT_HOSTS.some((d) => u.hostname.includes(d));
      } catch { continue; }
    } else if (isOrderPath) {
      try { resolvedUrl = new URL(href, baseUrl).href; } catch { continue; }
    } else {
      continue;
    }

    if (isOrderPath) orderCandidates.push(resolvedUrl);
    else if (isExternal) externalCandidates.push(resolvedUrl);
  }

  // Order/menu-path links take priority over generic external links, since
  // they're far more likely to lead to the actual ordering platform.
  const unique = [...new Set([...orderCandidates, ...externalCandidates])]
    .filter((u) => !visited.has(u))
    .slice(0, 4);
  console.log(`[Menufy links] ${baseUrl} (depth ${depthRemaining}) → candidates: ${JSON.stringify(unique)}`);

  for (const candidateUrl of unique) {
    try {
      const r = await fetch(candidateUrl, {
        signal: AbortSignal.timeout(5000),
        headers: { "User-Agent": "Mozilla/5.0 (compatible; SeeFood/1.0)", Accept: "text/html" },
      });
      if (!r.ok) {
        console.log(`[Menufy links] ${candidateUrl} → HTTP ${r.status}`);
        continue;
      }
      const linkedHtml = await r.text();

      if (linkedHtml.includes("api.menufy.com")) {
        console.log(`[Menufy] found via link: ${candidateUrl}`);
        const items = await parseMenufySite(candidateUrl, linkedHtml);
        if (items.length > 0) return items;
      }

      // Not a Menufy page itself — but it may link onward to one
      // (e.g. an intermediate "/order" redirect page). Recurse.
      const nested = await checkLinksForMenufy(candidateUrl, linkedHtml, depthRemaining - 1, visited);
      if (nested.length > 0) return nested;
    } catch { continue; }
  }
  return [];
}

async function parseMenufySite(url: string, html: string): Promise<MenuItemData[]> {
  const params = extractMenufyParams(html);
  console.log(`[Menufy] ${url} params: ${params ? `locationId=${params.locationId}` : "NOT FOUND"}`);

  // Strategy A: direct API call (fast, free)
  if (params) {
    const items = await fetchMenufyAPI(params.locationId, params.apiKey, url);
    if (items.length > 0) {
      console.log(`[Menufy API] ${url}: ${items.length} items`);
      return items;
    }
  }

  // Strategy B: Scrapfly with render_js=true (needs SCRAPFLY_KEY)
  const scrapflyKey = process.env.SCRAPFLY_KEY;
  if (scrapflyKey) {
    const items = await fetchMenufyViaScrapfly(url, scrapflyKey);
    if (items.length > 0) {
      console.log(`[Menufy Scrapfly] ${url}: ${items.length} items`);
      return items;
    }
  }

  console.log(`[Menufy] no data retrieved for ${url}`);
  return [];
}

/**
 * Try multiple Menufy API endpoint patterns server-side.
 * CORS doesn't apply server-side, so these calls work from Vercel even though
 * they fail from the browser. The api-key in the HTML is the public site key.
 */
async function fetchMenufyAPI(
  locationId: string,
  apiKey: string,
  siteUrl: string
): Promise<MenuItemData[]> {
  // Derive the site origin for the Referer header
  let origin = "https://restaurant.menufy.com";
  try { origin = new URL(siteUrl).origin; } catch {}

  const headers: Record<string, string> = {
    Authorization: `Basic ${apiKey}`,
    Accept: "application/json",
    "X-Api-Key": apiKey,
    Referer: `${origin}/`,
    Origin: origin,
  };

  // Known Menufy API endpoint candidates — try all, return first with data
  const candidates = [
    // Menu items (flat list, most useful)
    `https://api.menufy.com/v1/menuitems?locationId=${locationId}`,
    `https://api.menufy.com/v1/locations/${locationId}/menuitems`,
    // Categories (nested, contains items)
    `https://api.menufy.com/v1/categories?locationId=${locationId}`,
    `https://api.menufy.com/v1/locations/${locationId}/categories`,
    // Alternative patterns
    `https://api.menufy.com/restaurant/${locationId}/menu`,
    `https://api.menufy.com/v2/locations/${locationId}/menuitems`,
    // Site settings (may contain menu)
    `https://api.menufy.com/v1/sitesettings/locations/${locationId}`,
  ];

  for (const endpoint of candidates) {
    try {
      const res = await fetch(endpoint, {
        headers,
        signal: AbortSignal.timeout(5000),
      });
      if (!res.ok) {
        console.log(`[Menufy API] ${res.status} for ${endpoint}`);
        continue;
      }
      const data = await res.json();
      const items = parseMenufyApiData(data);
      if (items.length > 0) {
        console.log(`[Menufy API] ✓ endpoint: ${endpoint} → ${items.length} items`);
        return items;
      }
    } catch {
      continue;
    }
  }
  return [];
}

/** Walk any Menufy API response shape and extract MenuItemData. */
function parseMenufyApiData(data: unknown): MenuItemData[] {
  if (!data || typeof data !== "object") return [];
  const items: MenuItemData[] = [];
  walkMenufyApiNode(data, items);
  return deduplicateMenuItems(items);
}

function walkMenufyApiNode(obj: unknown, out: MenuItemData[]): void {
  if (!obj || typeof obj !== "object") return;
  if (Array.isArray(obj)) { obj.forEach((v) => walkMenufyApiNode(v, out)); return; }

  const o = obj as Record<string, unknown>;

  // Menufy API items always have a price; categories (which also carry a
  // name + optional description) don't. Require price to avoid misreading
  // category listings as dishes.
  if (
    typeof o.name === "string" &&
    o.name.trim().length > 1 &&
    (typeof o.price === "number" || typeof o.price === "string")
  ) {
    const item: MenuItemData = { name: o.name.trim() };
    const desc = (o.description as string | undefined)?.trim();
    if (desc) item.description = desc.substring(0, 300);
    const img = o.imageUrl ?? o.image ?? o.photo;
    if (typeof img === "string" && img.startsWith("http")) {
      item.imageUrl = upscaleHungerRushUrl(img);
    }
    out.push(item);
    return; // Don't recurse into an item's own children (avoid picking up modifier groups etc.)
  }

  for (const val of Object.values(o)) {
    if (val && typeof val === "object") walkMenufyApiNode(val, out);
  }
}

/**
 * Scrapfly fallback: render_js=true captures the fully JS-rendered DOM
 * and then we parse <new-menufy-item-card> element attributes from the HTML.
 */
async function fetchMenufyViaScrapfly(
  url: string,
  apiKey: string
): Promise<MenuItemData[]> {
  try {
    const scrapUrl =
      `https://api.scrapfly.io/scrape` +
      `?key=${apiKey}` +
      `&url=${encodeURIComponent(url)}` +
      `&asp=true&render_js=true&country=us` +
      `&wait_for_selector=new-menufy-item-card` +
      `&cost_budget=20`; // render_js costs more; cap at 20 credits

    const res = await fetch(scrapUrl, { signal: AbortSignal.timeout(35000) });
    if (!res.ok) {
      console.error(`[Menufy Scrapfly] HTTP ${res.status}`);
      return [];
    }
    const data = await res.json();
    const html = data.result?.content;
    if (!html) return [];

    return parseMenufyItemCards(html);
  } catch (e) {
    console.error("[Menufy Scrapfly] failed:", e);
    return [];
  }
}

/**
 * Parse <new-menufy-item-card> element attributes from a rendered HTML string.
 * Works on Scrapfly-rendered HTML where elements have been added to the DOM.
 * Each card has: item-name, item-description, item-image-url, item-price, item-id.
 */
function parseMenufyItemCards(html: string): MenuItemData[] {
  const items: MenuItemData[] = [];
  const cardPattern = /<new-menufy-item-card([^>]+)>/gi;
  let match: RegExpExecArray | null;

  while ((match = cardPattern.exec(html)) !== null) {
    const attrs = match[1];
    const name = extractHtmlAttr(attrs, "item-name");
    if (!name || name.length < 2) continue;

    const item: MenuItemData = { name };
    const desc = extractHtmlAttr(attrs, "item-description");
    if (desc) item.description = desc.substring(0, 300);

    const imgUrl = extractHtmlAttr(attrs, "item-image-url");
    if (imgUrl?.startsWith("http")) {
      item.imageUrl = upscaleHungerRushUrl(imgUrl);
    }

    items.push(item);
  }

  return deduplicateMenuItems(items);
}

/** Extract a named attribute value from an HTML attribute string. */
function extractHtmlAttr(attrs: string, name: string): string | null {
  const re = new RegExp(`\\b${name}="([^"]*)"`, "i");
  const m = attrs.match(re);
  if (!m) return null;
  return m[1]
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .trim();
}

/**
 * HungerRush CDN serves images at 300×300 by default in the Menufy site.
 * Upscale to 800×800 for better quality in our gallery.
 * URL pattern: width=300,height=300,fit=scale-down,format=auto/{ts}+{id}.png
 */
function upscaleHungerRushUrl(url: string): string {
  return url
    .replace("width=300,height=300,fit=scale-down", "width=800,height=800,fit=scale-down")
    .replace("width=300,height=300,fit=crop", "width=800,height=800,fit=scale-down");
}

// ── Schema.org parser ─────────────────────────────────────────────────────────

function parseSchemaOrgMenuItems(html: string): MenuItemData[] {
  const results: MenuItemData[] = [];
  const pattern =
    /<script[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;
  let m: RegExpExecArray | null;
  while ((m = pattern.exec(html)) !== null) {
    try {
      results.push(...walkSchemaNode(JSON.parse(m[1])));
    } catch {
      // Malformed JSON block — skip
    }
  }
  return deduplicateMenuItems(results.filter((i) => i.name.length >= 3 && i.name.length <= 80));
}

function walkSchemaNode(node: unknown): MenuItemData[] {
  if (!node || typeof node !== "object") return [];
  if (Array.isArray(node)) return node.flatMap(walkSchemaNode);

  const obj = node as Record<string, unknown>;
  const results: MenuItemData[] = [];
  const type = String(obj["@type"] ?? "").toLowerCase();

  if (type === "menuitem" && typeof obj.name === "string" && obj.name.trim()) {
    const item: MenuItemData = { name: obj.name.trim() };
    if (typeof obj.description === "string" && obj.description.trim()) {
      item.description = obj.description.trim().substring(0, 300);
    }
    const img = obj.image;
    if (typeof img === "string" && img.startsWith("http")) {
      item.imageUrl = img;
    } else if (Array.isArray(img) && typeof img[0] === "string" && (img[0] as string).startsWith("http")) {
      item.imageUrl = img[0] as string;
    } else if (img && typeof img === "object") {
      const imgObj = img as Record<string, unknown>;
      if (typeof imgObj.url === "string" && imgObj.url.startsWith("http")) {
        item.imageUrl = imgObj.url;
      }
    }
    results.push(item);
  }

  for (const val of Object.values(obj)) {
    if (val && typeof val === "object") results.push(...walkSchemaNode(val));
  }
  return results;
}

// ── Shared helpers ────────────────────────────────────────────────────────────

function deduplicateMenuItems(items: MenuItemData[]): MenuItemData[] {
  const seen = new Set<string>();
  return items.filter((item) => {
    const key = item.name.toLowerCase().trim();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}
