/**
 * Shared URL → MenuItemData[] extractor.
 *
 * Fetches a restaurant's own website and pulls dish names, descriptions, and
 * photo URLs from multiple sources.
 *
 * Platform detection order (first match wins):
 *   1. Menufy / HungerRush — web-component ordering sites.
 *      Detection: `api.menufy.com` in HTML.
 *      Data: direct API at api.menufy.com → falls back to Scrapfly render.
 *      Photos: static.hungerrush.com CDN — 300×300, scaled to 800×800.
 *      Coverage: thousands of independent US restaurants.
 *
 *   2. Schema.org LD+JSON — auto-generated by Toast, Square, Squarespace, Wix, Olo.
 *      Coverage: ~35–50% of restaurants with a website.
 *
 * Called by:
 *   - google.ts → restaurant's own website (Place Details `website` field)
 */

import { MenuItemData } from "./types";
import { hasScrapflyBudget } from "./scrapflyUsage";

export interface WebsiteExtractResult {
  items: MenuItemData[];
  /** Generic food-photo candidates scraped from the page(s) visited — no
   * trusted name attached, so these get fed through the same Gemini
   * identification pass as raw Google photos (see google.ts). */
  photoUrls: string[];
}

/** Detection chain run against a single already-fetched page. */
async function extractFromPage(url: string, html: string): Promise<WebsiteExtractResult> {
  // ── Platform 1: Menufy / HungerRush ───────────────────────────────────────
  if (html.includes("api.menufy.com")) {
    const items = await parseMenufySite(url, html);
    if (items.length > 0) return { items, photoUrls: [] };
  }

  // ── Platform 1b: Menufy via order link ───────────────────────────────────
  // Some restaurants (e.g. Richie's Diner) have their marketing site separate
  // from their Menufy ordering site, sometimes chained through an intermediate
  // "/order" redirect page. Follow up to 3 hops.
  const menufyViaSideLink = await checkLinksForMenufy(url, html, 3);
  if (menufyViaSideLink.length > 0) return { items: menufyViaSideLink, photoUrls: [] };

  // ── Platform 3: Named ordering platforms (Toast, Square, Clover, ChowNow, Olo, PopMenu)
  // Real-world finding (July 2026, live restaurants): these sites almost never
  // embed menu JSON in the raw HTML of the marketing page. Toast restaurants
  // typically just *link* to a separate toasttab.com ordering page (same 2-hop
  // pattern as Menufy). Square/ChowNow/Clover/Olo/PopMenu render their menu
  // entirely client-side (JS SPA) — nothing useful in the raw HTML at all.
  const platform = detectOrderingPlatform(html);
  let renderedHtml: string | null = null;
  let renderedUrl = url;
  if (platform) {
    let items = extractEmbeddedJsonMenuItems(html, platform);

    if (items.length === 0) {
      const platformUrl = findOrderingPlatformLink(html, url, platform) ?? url;

      // Toast's ASP challenge costs ~51 Scrapfly credits/attempt — the same
      // expensive tier that got DoorDash banned from the live path (see
      // DECISIONS.md). Never spend Scrapfly credits on Toast; it's crawler-only.
      if (platform !== "toast" && process.env.SCRAPFLY_KEY) {
        const rendered = await fetchOrderingPlatformViaScrapfly(platformUrl, platform);
        items = rendered.items;
        renderedHtml = rendered.renderedHtml;
        renderedUrl = platformUrl;
      }
    }

    if (items.length > 0) return { items, photoUrls: [] };
  }

  // ── Platform 2: Schema.org LD+JSON ────────────────────────────────────────
  // Universal fallback — these platforms often also emit schema.org for SEO
  // even when their own embedded JSON isn't present in the raw (unrendered) HTML.
  // When a Scrapfly render happened above but still found no structured
  // items, run this same fallback against the RENDERED HTML too — confirmed
  // live (Le Coffee Shop): the render succeeds with real post-JS content,
  // which the raw pre-JS HTML never has, so checking only the raw HTML here
  // was silently discarding real photos every time a JS SPA platform's
  // structured extraction came up empty.
  const rawResult = parseSchemaOrgMenuItems(html);
  const rawPhotos = extractGenericPageImages(html, url);
  if (rawResult.length > 0 || !renderedHtml) {
    return { items: rawResult, photoUrls: rawPhotos };
  }
  const renderedResult = parseSchemaOrgMenuItems(renderedHtml);
  const renderedPhotos = extractGenericPageImages(renderedHtml, renderedUrl);
  return {
    items: renderedResult,
    photoUrls: [...rawPhotos, ...renderedPhotos].slice(0, 20),
  };
}

export async function fetchMenuFromUrl(url: string): Promise<WebsiteExtractResult> {
  try {
    const res = await fetch(url, {
      signal: AbortSignal.timeout(6000),
      headers: {
        "User-Agent": "Mozilla/5.0 (compatible; SeeFood/1.0)",
        Accept: "text/html,application/xhtml+xml",
      },
    });
    if (!res.ok) {
      console.log(`[fetchMenuFromUrl] ${url} → HTTP ${res.status}`);
      return { items: [], photoUrls: [] };
    }
    const html = await res.text();
    const primary = await extractFromPage(url, html);

    // The Place Details `website` field is often the marketing/location
    // landing page, not the actual menu page — confirmed live (Bluewater
    // Grill: the location page has only a logo + hero banner, while its
    // real /temecula-menu page has dozens of real MenuItem entries across
    // several schema.org Menu blocks). If nothing structured came off the
    // primary page, follow a generic "menu" link and try again there too —
    // this is a hard fallback (not platform-specific), so it applies broadly
    // to any independent restaurant site, not just known platforms.
    if (primary.items.length === 0) {
      // Generic nav links (e.g. "/menu/") are often a locations chooser, not
      // a specific location's real menu — try every distinct candidate and
      // keep whichever actually yields structured items, rather than
      // trusting the first/shortest link found.
      const menuLinks = findGenericMenuPageLinks(html, url).filter((l) => l !== url);
      let best: WebsiteExtractResult | null = null;
      for (const menuLink of menuLinks) {
        try {
          const menuRes = await fetch(menuLink, {
            signal: AbortSignal.timeout(6000),
            headers: {
              "User-Agent": "Mozilla/5.0 (compatible; SeeFood/1.0)",
              Accept: "text/html,application/xhtml+xml",
            },
          });
          if (!menuRes.ok) continue;
          const menuHtml = await menuRes.text();
          const fromMenuPage = await extractFromPage(menuLink, menuHtml);
          if (fromMenuPage.items.length > 0) {
            best = fromMenuPage;
            break; // first candidate with real structured data wins
          }
          if (!best || fromMenuPage.photoUrls.length > best.photoUrls.length) {
            best = fromMenuPage; // no items anywhere yet — keep the one with the most photos
          }
        } catch (e) {
          console.error(`[fetchMenuFromUrl] menu-link follow ${menuLink} failed:`, e);
        }
      }
      if (best) {
        return {
          items: best.items,
          photoUrls: [...primary.photoUrls, ...best.photoUrls].slice(0, 20),
        };
      }
    }

    return primary;
  } catch (e) {
    console.error(`[fetchMenuFromUrl] ${url} failed:`, e);
    return { items: [], photoUrls: [] };
  }
}

/**
 * Generic (non-platform-specific) "find the menu page" fallback — looks for
 * an anchor whose href or link text mentions "menu", same-origin only.
 * Deliberately permissive: a wrong guess just means the follow-up page also
 * yields nothing (fail-open), so a false positive costs one wasted fetch.
 */
function findGenericMenuPageLinks(html: string, baseUrl: string): string[] {
  let origin = "";
  try { origin = new URL(baseUrl).origin; } catch { return []; }

  const anchorPattern = /<a\s[^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/gi;
  let m: RegExpExecArray | null;
  // Generic nav links like "/menu/" are usually a locations chooser, not a
  // specific location's actual menu — confirmed live (Bluewater Grill: "/menu/"
  // is an Organization-level page with zero MenuItem schema, while the real
  // content sits at the more specific "/temecula-menu" button link further
  // down the page). Try every distinct candidate rather than just the first
  // and let the caller keep whichever actually yields structured data —
  // ranking by link specificity (path length) is a reasonable prior but not
  // reliable enough to trust alone.
  const candidates: string[] = [];
  const seenPaths = new Set<string>();
  while ((m = anchorPattern.exec(html)) !== null) {
    const href = m[1];
    const text = m[2].replace(/<[^>]+>/g, "").trim().toLowerCase();
    if (!href || href.startsWith("#") || href.startsWith("javascript") || href.startsWith("mailto") || href.startsWith("tel")) continue;
    const hrefLower = href.toLowerCase();
    if (!hrefLower.includes("menu") && text !== "menu" && !text.includes("our menu") && !text.includes("view menu")) continue;
    if (/mobile-menu|nav-menu|menu-toggle|menu-icon/.test(hrefLower)) continue;
    try {
      const resolved = new URL(href, baseUrl);
      if (resolved.origin !== origin) continue;
      const pathKey = resolved.pathname; // dedupe by path, ignore #fragments
      if (seenPaths.has(pathKey)) continue;
      seenPaths.add(pathKey);
      candidates.push(resolved.origin + resolved.pathname);
    } catch {
      continue;
    }
  }
  // Longer/more specific paths first (heuristic prior; caller still tries all).
  return candidates.sort((a, b) => b.length - a.length).slice(0, 3);
}

const IMAGE_URL_RE = /<img[^>]+src="([^"]+)"/gi;
const NON_FOOD_IMAGE_HINTS = /logo|icon|favicon|sprite|avatar|placeholder|\.svg(\?|$)|social|facebook|instagram|twitter|tripadvisor|yelp|pixel|analytics|badge|button/i;

/**
 * Scrape plausible food-photo URLs directly off a page's <img> tags — the
 * fallback for restaurant sites whose schema.org MenuItem entries have no
 * `image` (common: menu text is structured, photos aren't), so structured
 * parsing alone still leaves the corpus photo-starved even though real
 * photography exists on the same page. These have no trusted dish name, so
 * they're treated like raw Google candidates and go through the same Gemini
 * identification pass (google.ts), not the pre-labeled/trusted path.
 */
function extractGenericPageImages(html: string, baseUrl: string): string[] {
  const urls: string[] = [];
  const seen = new Set<string>();
  let m: RegExpExecArray | null;
  while ((m = IMAGE_URL_RE.exec(html)) !== null) {
    const src = m[1];
    if (!src || NON_FOOD_IMAGE_HINTS.test(src)) continue;
    if (!/\.(jpe?g|png|webp)(\?|$)/i.test(src)) continue;
    try {
      const resolved = new URL(src, baseUrl).href;
      if (seen.has(resolved)) continue;
      seen.add(resolved);
      urls.push(resolved);
    } catch {
      continue;
    }
    if (urls.length >= 15) break;
  }
  return urls;
}

// ── Menufy / HungerRush ───────────────────────────────────────────────────────
//
// Architecture:
//   Web components (<new-menufy-item-card>) are populated from api.menufy.com.
//   The raw HTML exposes location-id + api-key in <location-context> attributes.
//   The data is NOT in the raw HTML (JS-rendered), so we need one of:
//     A. Direct API call to api.menufy.com (fast, free, no credits)
//     B. Scrapfly render_js=true to get fully-rendered DOM (needs SCRAPFLY_KEY)
//
// Each item card attribute pattern:
//   item-name="Baby Back BBQ Ribs"
//   item-description="2 full racks..."
//   item-image-url="https://static.hungerrush.com/menufy/width=300,.../{ts}+{id}.png"
//   item-price="89.95"  item-id="12331076"  category-id="1131672"

function extractMenufyParams(html: string): { locationId: string; apiKey: string } | null {
  const locationMatch = html.match(/location-id="(\d+)"/);
  const apiKeyMatch   = html.match(/api-key="([A-Za-z0-9+/=]{8,})"/);
  if (!locationMatch || !apiKeyMatch) return null;
  return { locationId: locationMatch[1], apiKey: apiKeyMatch[1] };
}

/**
 * Follow "order" / "menu" links on the main website to find a Menufy
 * ordering site that's hosted at a different domain.
 * Example: richiesdiner.com → richiesdinertemecula.com (Menufy)
 */
async function checkLinksForMenufy(
  baseUrl: string,
  html: string,
  depthRemaining: number,
  visited: Set<string> = new Set()
): Promise<MenuItemData[]> {
  if (depthRemaining <= 0) return [];
  visited.add(baseUrl);
  let baseOrigin = "";
  try { baseOrigin = new URL(baseUrl).origin; } catch { return []; }

  // Find candidate links from actual anchor tags only — <a href="...">,
  // NOT <link>/<img>/<script> resource hrefs (favicons, fonts, CDN assets),
  // which otherwise flood the candidate list and crowd out the real link.
  const anchorPattern = /<a\s[^>]*href="([^"]+)"/gi;
  const STATIC_ASSET_RE = /\.(css|js|png|jpe?g|gif|svg|ico|woff2?|ttf|eot|json|xml|webmanifest)(\?|#|$)/i;
  const NON_CONTENT_HOSTS = [
    "facebook.com","instagram.com","yelp.com","google.com","tripadvisor.com","twitter.com","x.com",
    "tiktok.com","doordash.com","ubereats.com","grubhub.com","typekit.net","adobedtm.com",
    "cookielaw.org","squarespace-cdn.com","squarespace.com","googletagmanager.com","google-analytics.com",
  ];

  const orderCandidates: string[] = [];
  const externalCandidates: string[] = [];
  let m: RegExpExecArray | null;

  while ((m = anchorPattern.exec(html)) !== null) {
    const href = m[1];
    if (!href || href.startsWith("#") || href.startsWith("javascript") ||
        href.startsWith("mailto") || href.startsWith("tel")) continue;
    if (STATIC_ASSET_RE.test(href)) continue;

    // Order/menu keywords in relative paths
    const isOrderPath = /\/(order|menu|delivery|online-order)/i.test(href);

    let isExternal = false;
    let resolvedUrl = href;
    if (href.startsWith("http")) {
      try {
        const u = new URL(href);
        isExternal = u.origin !== baseOrigin && !NON_CONTENT_HOSTS.some((d) => u.hostname.includes(d));
      } catch { continue; }
    } else if (isOrderPath) {
      try { resolvedUrl = new URL(href, baseUrl).href; } catch { continue; }
    } else {
      continue;
    }

    if (isOrderPath) orderCandidates.push(resolvedUrl);
    else if (isExternal) externalCandidates.push(resolvedUrl);
  }

  // Order/menu-path links take priority over generic external links, since
  // they're far more likely to lead to the actual ordering platform.
  const unique = [...new Set([...orderCandidates, ...externalCandidates])]
    .filter((u) => !visited.has(u))
    .slice(0, 4);
  console.log(`[Menufy links] ${baseUrl} (depth ${depthRemaining}) → candidates: ${JSON.stringify(unique)}`);

  for (const candidateUrl of unique) {
    try {
      const r = await fetch(candidateUrl, {
        signal: AbortSignal.timeout(5000),
        headers: { "User-Agent": "Mozilla/5.0 (compatible; SeeFood/1.0)", Accept: "text/html" },
      });
      if (!r.ok) {
        console.log(`[Menufy links] ${candidateUrl} → HTTP ${r.status}`);
        continue;
      }
      const linkedHtml = await r.text();

      if (linkedHtml.includes("api.menufy.com")) {
        console.log(`[Menufy] found via link: ${candidateUrl}`);
        const items = await parseMenufySite(candidateUrl, linkedHtml);
        if (items.length > 0) return items;
      }

      // Not a Menufy page itself — but it may link onward to one
      // (e.g. an intermediate "/order" redirect page). Recurse.
      const nested = await checkLinksForMenufy(candidateUrl, linkedHtml, depthRemaining - 1, visited);
      if (nested.length > 0) return nested;
    } catch { continue; }
  }
  return [];
}

async function parseMenufySite(url: string, html: string): Promise<MenuItemData[]> {
  const params = extractMenufyParams(html);
  console.log(`[Menufy] ${url} params: ${params ? `locationId=${params.locationId}` : "NOT FOUND"}`);

  // Strategy A: direct API call (fast, free)
  if (params) {
    const items = await fetchMenufyAPI(params.locationId, params.apiKey, url);
    if (items.length > 0) {
      console.log(`[Menufy API] ${url}: ${items.length} items`);
      return items;
    }
  }

  // Strategy B: Scrapfly with render_js=true (needs SCRAPFLY_KEY)
  const scrapflyKey = process.env.SCRAPFLY_KEY;
  if (scrapflyKey) {
    const items = await fetchMenufyViaScrapfly(url, scrapflyKey);
    if (items.length > 0) {
      console.log(`[Menufy Scrapfly] ${url}: ${items.length} items`);
      return items;
    }
  }

  console.log(`[Menufy] no data retrieved for ${url}`);
  return [];
}

/**
 * Try multiple Menufy API endpoint patterns server-side.
 * CORS doesn't apply server-side, so these calls work from Vercel even though
 * they fail from the browser. The api-key in the HTML is the public site key.
 */
async function fetchMenufyAPI(
  locationId: string,
  apiKey: string,
  siteUrl: string
): Promise<MenuItemData[]> {
  // Derive the site origin for the Referer header
  let origin = "https://restaurant.menufy.com";
  try { origin = new URL(siteUrl).origin; } catch {}

  const headers: Record<string, string> = {
    Authorization: `Basic ${apiKey}`,
    Accept: "application/json",
    "X-Api-Key": apiKey,
    Referer: `${origin}/`,
    Origin: origin,
  };

  // Known Menufy API endpoint candidates — try all, return first with data
  const candidates = [
    // Menu items (flat list, most useful)
    `https://api.menufy.com/v1/menuitems?locationId=${locationId}`,
    `https://api.menufy.com/v1/locations/${locationId}/menuitems`,
    // Categories (nested, contains items)
    `https://api.menufy.com/v1/categories?locationId=${locationId}`,
    `https://api.menufy.com/v1/locations/${locationId}/categories`,
    // Alternative patterns
    `https://api.menufy.com/restaurant/${locationId}/menu`,
    `https://api.menufy.com/v2/locations/${locationId}/menuitems`,
    // Site settings (may contain menu)
    `https://api.menufy.com/v1/sitesettings/locations/${locationId}`,
  ];

  for (const endpoint of candidates) {
    try {
      const res = await fetch(endpoint, {
        headers,
        signal: AbortSignal.timeout(5000),
      });
      if (!res.ok) {
        console.log(`[Menufy API] ${res.status} for ${endpoint}`);
        continue;
      }
      const data = await res.json();
      const items = parseMenufyApiData(data);
      if (items.length > 0) {
        console.log(`[Menufy API] ✓ endpoint: ${endpoint} → ${items.length} items`);
        return items;
      }
    } catch {
      continue;
    }
  }
  return [];
}

/** Walk any Menufy API response shape and extract MenuItemData. */
export function parseMenufyApiData(data: unknown): MenuItemData[] {
  if (!data || typeof data !== "object") return [];
  const items: MenuItemData[] = [];
  walkMenufyApiNode(data, items);
  return deduplicateMenuItems(items);
}

function walkMenufyApiNode(obj: unknown, out: MenuItemData[]): void {
  if (!obj || typeof obj !== "object") return;
  if (Array.isArray(obj)) { obj.forEach((v) => walkMenufyApiNode(v, out)); return; }

  const o = obj as Record<string, unknown>;

  // Menufy API items always have a price; categories (which also carry a
  // name + optional description) don't. Require price to avoid misreading
  // category listings as dishes.
  if (
    typeof o.name === "string" &&
    o.name.trim().length > 1 &&
    (typeof o.price === "number" || typeof o.price === "string")
  ) {
    const item: MenuItemData = { name: decodeHtmlEntities(o.name), source: "menufy" };
    const desc = (o.description as string | undefined)?.trim();
    if (desc) item.description = decodeHtmlEntities(desc).substring(0, 300);
    const img = o.imageUrl ?? o.image ?? o.photo;
    if (typeof img === "string" && img.startsWith("http")) {
      item.imageUrl = upscaleHungerRushUrl(img);
    }
    if (typeof o.price === "number") item.price = o.price;
    else if (typeof o.price === "string" && !isNaN(parseFloat(o.price))) item.price = parseFloat(o.price);
    out.push(item);
    return; // Don't recurse into an item's own children (avoid picking up modifier groups etc.)
  }

  for (const val of Object.values(o)) {
    if (val && typeof val === "object") walkMenufyApiNode(val, out);
  }
}

/**
 * Scrapfly fallback: render_js=true captures the fully JS-rendered DOM
 * and then we parse <new-menufy-item-card> element attributes from the HTML.
 */
async function fetchMenufyViaScrapfly(
  url: string,
  apiKey: string
): Promise<MenuItemData[]> {
  if (!(await hasScrapflyBudget())) {
    console.warn("[Menufy Scrapfly] skipped — free-tier budget cap reached");
    return [];
  }
  try {
    const scrapUrl =
      `https://api.scrapfly.io/scrape` +
      `?key=${apiKey}` +
      `&url=${encodeURIComponent(url)}` +
      `&asp=true&render_js=true&country=us` +
      `&wait_for_selector=new-menufy-item-card` +
      `&cost_budget=20`; // render_js costs more; cap at 20 credits

    const res = await fetch(scrapUrl, { signal: AbortSignal.timeout(35000) });
    if (!res.ok) {
      console.error(`[Menufy Scrapfly] HTTP ${res.status}`);
      return [];
    }
    const data = await res.json();
    const html = data.result?.content;
    if (!html) return [];

    return parseMenufyItemCards(html);
  } catch (e) {
    console.error("[Menufy Scrapfly] failed:", e);
    return [];
  }
}

/**
 * Parse <new-menufy-item-card> element attributes from a rendered HTML string.
 * Works on Scrapfly-rendered HTML where elements have been added to the DOM.
 * Each card has: item-name, item-description, item-image-url, item-price, item-id.
 */
export function parseMenufyItemCards(html: string): MenuItemData[] {
  const items: MenuItemData[] = [];
  const cardPattern = /<new-menufy-item-card([^>]+)>/gi;
  let match: RegExpExecArray | null;

  while ((match = cardPattern.exec(html)) !== null) {
    const attrs = match[1];
    const name = extractHtmlAttr(attrs, "item-name");
    if (!name || name.length < 2) continue;

    const item: MenuItemData = { name, source: "menufy" };
    const desc = extractHtmlAttr(attrs, "item-description");
    if (desc) item.description = desc.substring(0, 300);

    const imgUrl = extractHtmlAttr(attrs, "item-image-url");
    if (imgUrl?.startsWith("http")) {
      item.imageUrl = upscaleHungerRushUrl(imgUrl);
    }

    const priceAttr = extractHtmlAttr(attrs, "item-price");
    if (priceAttr && !isNaN(parseFloat(priceAttr))) item.price = parseFloat(priceAttr);

    items.push(item);
  }

  return deduplicateMenuItems(items);
}

/**
 * Decode the small set of HTML entities that show up in scraped dish names —
 * some sources (Menufy's JSON API included) hand back literal entity text
 * even outside of raw HTML, e.g. "&nbsp;Chicken-like Fried Steak" rendered
 * verbatim in the grid. &amp; must run last so it doesn't re-decode entities
 * produced by the other replacements.
 */
function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&nbsp;/g, " ")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, "&")
    .replace(/\s+/g, " ")
    .trim();
}

/** Extract a named attribute value from an HTML attribute string. */
function extractHtmlAttr(attrs: string, name: string): string | null {
  const re = new RegExp(`\\b${name}="([^"]*)"`, "i");
  const m = attrs.match(re);
  if (!m) return null;
  return decodeHtmlEntities(m[1]);
}

/**
 * HungerRush CDN serves images at 300×300 by default in the Menufy site.
 * Upscale to 800×800 for better quality in our gallery.
 * URL pattern: width=300,height=300,fit=scale-down,format=auto/{ts}+{id}.png
 */
function upscaleHungerRushUrl(url: string): string {
  return url
    .replace("width=300,height=300,fit=scale-down", "width=800,height=800,fit=scale-down")
    .replace("width=300,height=300,fit=crop", "width=800,height=800,fit=scale-down");
}

// ── Named ordering platforms ──────────────────────────────────────────────────
// Toast, Square Online, Clover, ChowNow, Olo, and PopMenu all render their menu
// client-side from a JSON blob embedded in the page (or loaded async from their
// own domain). Detection signatures are stable brand/CDN hostnames; extraction
// reuses the same "walk any JSON for {name + (price|description|image)} shaped
// nodes" technique as the Menufy API parser, since the exact internal schema of
// each platform isn't publicly documented and will drift — the walker is
// resilient to field reordering/renaming as long as the shape holds.
//
// Coverage confidence: real (detection signatures are well-known, stable
// hostnames). Extraction confidence: best-effort until proven against a live
// restaurant on each platform — the benchmark scoreboard is the tripwire; a
// platform with 0% hit rate across restaurants confirmed to use it needs its
// extractor revisited.

type OrderingPlatform = "toast" | "square" | "clover" | "chownow" | "olo" | "popmenu";

const PLATFORM_SIGNATURES: Array<{ platform: OrderingPlatform; test: (html: string) => boolean }> = [
  { platform: "toast", test: (h) => h.includes("toasttab.com") },
  { platform: "chownow", test: (h) => h.includes("chownow.com") || h.includes("chownow-order") },
  { platform: "olo", test: (h) => h.includes("static.olo.com") || h.includes("olo.com/menu") },
  { platform: "clover", test: (h) => h.includes("clover.com/online-ordering") || h.includes("clover-ecomm") },
  { platform: "square", test: (h) => h.includes(".square.site") || h.includes("squareup.com/checkout") },
  { platform: "popmenu", test: (h) => h.includes("popmenu.com") || h.includes("cdn.popmenu.com") },
];

export function detectOrderingPlatform(html: string): OrderingPlatform | null {
  for (const { platform, test } of PLATFORM_SIGNATURES) {
    if (test(html)) return platform;
  }
  return null;
}

const PLATFORM_HOSTNAME_HINTS: Record<OrderingPlatform, string[]> = {
  toast: ["toasttab.com"],
  chownow: ["chownow.com"],
  olo: ["olo.com"],
  clover: ["clover.com"],
  square: ["square.site", "squareup.com"],
  popmenu: ["popmenu.com"],
};

/**
 * Find an <a href> on the marketing page pointing to the platform's own
 * ordering domain (e.g. a restaurant site linking out to toasttab.com). Most
 * restaurants on these platforms link out rather than embed — same pattern as
 * Menufy's separate ordering site.
 */
function findOrderingPlatformLink(html: string, baseUrl: string, platform: OrderingPlatform): string | null {
  const hints = PLATFORM_HOSTNAME_HINTS[platform];
  const anchorPattern = /<a\s[^>]*href="([^"]+)"/gi;
  let m: RegExpExecArray | null;
  while ((m = anchorPattern.exec(html)) !== null) {
    const href = m[1];
    if (hints.some((h) => href.includes(h))) {
      try {
        return new URL(href, baseUrl).href;
      } catch {
        continue;
      }
    }
  }
  return null;
}

/**
 * Render fallback for platforms whose menu is client-side JS (Square Online,
 * ChowNow, Clover, Olo, PopMenu observed to load menu data only after JS runs —
 * confirmed live, none embed it in raw HTML). NEVER call this for "toast" —
 * its ASP challenge costs the same 51+ Scrapfly credits/attempt that got
 * DoorDash banned from the live path; see DECISIONS.md.
 */
/**
 * Returns both the parsed items AND the rendered HTML (when the render
 * succeeded) — confirmed live (Le Coffee Shop, July 2026): the render often
 * succeeds (200, real post-JS content) while item extraction still finds
 * nothing, because "renders the JS" and "finds the menu content" are
 * different problems. Discarding the rendered HTML after a failed item
 * extraction meant the caller never got a second chance to pull real food
 * photos or schema.org data out of it via the generic fallbacks.
 */
async function fetchOrderingPlatformViaScrapfly(
  url: string,
  platform: OrderingPlatform
): Promise<{ items: MenuItemData[]; renderedHtml: string | null }> {
  const scrapflyKey = process.env.SCRAPFLY_KEY;
  if (!scrapflyKey || platform === "toast") return { items: [], renderedHtml: null };
  if (!(await hasScrapflyBudget())) {
    console.warn(`[${platform} Scrapfly] skipped — free-tier budget cap reached`);
    return { items: [], renderedHtml: null };
  }
  try {
    const scrapUrl =
      `https://api.scrapfly.io/scrape` +
      `?key=${scrapflyKey}` +
      `&url=${encodeURIComponent(url)}` +
      `&asp=true&render_js=true&country=us&cost_budget=30`;
    const res = await fetch(scrapUrl, { signal: AbortSignal.timeout(35000) });
    if (!res.ok) return { items: [], renderedHtml: null };
    const data = await res.json();
    const html = data.result?.content;
    if (!html) return { items: [], renderedHtml: null };
    return { items: extractEmbeddedJsonMenuItems(html, platform), renderedHtml: html };
  } catch (e) {
    console.error(`[${platform} Scrapfly] failed:`, e);
    return { items: [], renderedHtml: null };
  }
}

/** Scan every <script> block on the page for embedded JSON menu data. */
export function extractEmbeddedJsonMenuItems(html: string, source: OrderingPlatform): MenuItemData[] {
  const items: MenuItemData[] = [];
  const scriptPattern = /<script[^>]*>([\s\S]*?)<\/script>/gi;
  let m: RegExpExecArray | null;

  while ((m = scriptPattern.exec(html)) !== null) {
    const body = m[1].trim();
    if (!body || (!body.includes("{") && !body.includes("["))) continue;

    // Try the whole script body as JSON first (application/json blocks),
    // then fall back to extracting the first balanced {...} or [...] literal
    // from a `var x = {...}` / `window.x = {...}` assignment.
    const candidates: string[] = [body];
    const assignMatch = body.match(/=\s*(\{[\s\S]*\}|\[[\s\S]*\])\s*;?\s*$/);
    if (assignMatch) candidates.push(assignMatch[1]);

    for (const candidate of candidates) {
      try {
        const data = JSON.parse(candidate);
        walkGenericMenuNode(data, source, items);
      } catch {
        continue;
      }
    }
  }

  return deduplicateMenuItems(items);
}

function walkGenericMenuNode(obj: unknown, source: OrderingPlatform, out: MenuItemData[]): void {
  if (!obj || typeof obj !== "object") return;
  if (Array.isArray(obj)) { obj.forEach((v) => walkGenericMenuNode(v, source, out)); return; }

  const o = obj as Record<string, unknown>;
  const name = (o.name ?? o.itemName ?? o.title) as unknown;
  const price = o.price ?? o.basePrice ?? o.cost;
  const description = (o.description ?? o.desc) as unknown;
  const image = (o.imageUrl ?? o.image ?? o.photoUrl ?? o.thumbnailUrl) as unknown;

  const hasPrice = typeof price === "number" || (typeof price === "string" && !isNaN(parseFloat(price)));
  if (typeof name === "string" && name.trim().length > 1 && name.trim().length < 80 && hasPrice) {
    const item: MenuItemData = { name: decodeHtmlEntities(name), source };
    if (typeof description === "string" && description.trim()) {
      item.description = decodeHtmlEntities(description).substring(0, 300);
    }
    if (typeof image === "string" && image.startsWith("http")) item.imageUrl = image;
    item.price = typeof price === "number" ? price : parseFloat(price as string);
    out.push(item);
    return; // don't recurse into an item's own children (modifiers, etc.)
  }

  for (const val of Object.values(o)) {
    if (val && typeof val === "object") walkGenericMenuNode(val, source, out);
  }
}

// ── Schema.org parser ─────────────────────────────────────────────────────────

export function parseSchemaOrgMenuItems(html: string): MenuItemData[] {
  const results: MenuItemData[] = [];
  const pattern =
    /<script[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;
  let m: RegExpExecArray | null;
  while ((m = pattern.exec(html)) !== null) {
    try {
      results.push(...walkSchemaNode(JSON.parse(m[1])));
    } catch {
      // Malformed JSON block — skip
    }
  }
  return deduplicateMenuItems(results.filter((i) => i.name.length >= 3 && i.name.length <= 80));
}

function walkSchemaNode(node: unknown): MenuItemData[] {
  if (!node || typeof node !== "object") return [];
  if (Array.isArray(node)) return node.flatMap(walkSchemaNode);

  const obj = node as Record<string, unknown>;
  const results: MenuItemData[] = [];
  const type = String(obj["@type"] ?? "").toLowerCase();

  if (type === "menuitem" && typeof obj.name === "string" && obj.name.trim()) {
    const item: MenuItemData = { name: decodeHtmlEntities(obj.name), source: "schema_org" };
    if (typeof obj.description === "string" && obj.description.trim()) {
      item.description = decodeHtmlEntities(obj.description).substring(0, 300);
    }
    const img = obj.image;
    if (typeof img === "string" && img.startsWith("http")) {
      item.imageUrl = img;
    } else if (Array.isArray(img) && typeof img[0] === "string" && (img[0] as string).startsWith("http")) {
      item.imageUrl = img[0] as string;
    } else if (img && typeof img === "object") {
      const imgObj = img as Record<string, unknown>;
      if (typeof imgObj.url === "string" && imgObj.url.startsWith("http")) {
        item.imageUrl = imgObj.url;
      }
    }
    const offers = obj.offers as Record<string, unknown> | undefined;
    const rawPrice = offers?.price;
    if (typeof rawPrice === "number") item.price = rawPrice;
    else if (typeof rawPrice === "string" && !isNaN(parseFloat(rawPrice))) item.price = parseFloat(rawPrice);
    results.push(item);
  }

  for (const val of Object.values(obj)) {
    if (val && typeof val === "object") results.push(...walkSchemaNode(val));
  }
  return results;
}

// ── Shared helpers ────────────────────────────────────────────────────────────

function deduplicateMenuItems(items: MenuItemData[]): MenuItemData[] {
  const seen = new Set<string>();
  return items.filter((item) => {
    const key = item.name.toLowerCase().trim();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}
